---
output: github_document
bibliography: inst/REFERENCES.bib
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "65%",
  fig.align = "center"
)
```

## The `RcppCensSpatial R` package

<!-- badges: start -->
<!-- badges: end -->

The `RcppCensSpatial R` package provides functions to estimate parameters in spatial linear models with censored and missing responses via Expectation-Maximization (EM) [@dempster1977maximum], Stochastic Approximation EM (SAEM) [@delyon1999convergence], or Monte Carlo EM (MCEM) [@wei1990monte] algorithm. These algorithms are widely used to compute the maximum likelihood (ML) estimates in problems with incomplete data. The EM algorithm computes the ML estimates when a closed expression for the conditional expectation of the complete-data log-likelihood function is available. In the MCEM algorithm, the conditional expectation is substituted by a Monte Carlo approximation based on many independent simulations of the missing data. In contrast, the SAEM algorithm splits the E-step into simulation and integration steps.

This package approximates the standard error of the estimates using the method developed by [@louis1982finding]. Furthermore, it has a function that performs spatial prediction in new locations. It also allows computing the covariance matrix and the distance matrix. For more information about the model formulation and estimation, please see 
@ordonez2018geostatistical and @valeriano2021likelihood.

### Functions

`RcppCensSpatial` package provides the following functions:

* `CovMat`: Computes the spatial covariance matrix.
* `dist2Dmatrix`: Computes the Euclidean distance matrix for a set of coordinates.
* `EM.sclm`: Returns the ML estimates of the unknown parameters computed via the EM algorithm.
* `MCEM.sclm`: Returns the ML estimates of the unknown parameters computed via the MCEM algorithm.
* `SAEM.sclm`: Returns the ML estimates of the unknown parameters computed via the SAEM algorithm.
* `predict.sclm`: Performs spatial prediction in a set of new locations.
* `rCensSp`: Simulates censored spatial data for an established censoring rate.

Functions `print`, `summary`, `predict`, and `plot` also work for the `sclm` class.

### Installation

You can install the released version of `RcppCensSpatial` from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("RcppCensSpatial")
```

### References
